apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opa-exporter
  labels: 
    {{- include "clusterauditor.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - constraints.gatekeeper.sh
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
