{{- if .Values.servicemonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: opa-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clusterauditor.labels" . | nindent 4 }}
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
      {{- if .Values.servicemonitor.encryptedMetrics }}
      scheme: https
      tlsConfig:
        caFile: /etc/prom-certs/root-cert.pem
        certFile: /etc/prom-certs/cert-chain.pem
        keyFile: /etc/prom-certs/key.pem
        insecureSkipVerify: true  # Prometheus does not support Istio security naming, thus skip verifying target pod certificate
      {{- end }}
  selector:
    matchLabels:
      app: opa-exporter
{{- end }}
