apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "clusterauditor.labels" . | nindent 4 }}
  name: opa-exporter
  namespace: {{ .Release.Namespace }}
{{/* start TNT addition 
If false, a K8s API token will not be mounted in Pods utilizing this ServiceAccount, unless overriden at the Pod spec-level
In this case, this behavior -is- overriden at the Pod spec-level due to app requirements
*/}}
automountServiceAccountToken: false
{{/* end TNT addition */}}
