apiVersion: v1
kind: Service
metadata:
  labels:
    app: opa-exporter
    {{- include "clusterauditor.labels" . | nindent 4 }}
  name: opa-exporter
  namespace: {{ .Release.Namespace }}
  annotations:
    prometheus.io/scrape-slow: 'true'
spec:
  ports:
    - name: metrics
      port: 9141
      protocol: TCP
      appProtocol: "http"
      targetPort: 9141
  selector:
    app: opa-exporter
  type: ClusterIP
