annotations: {}

image:
  repo: mcelep/opa_scorecard_exporter
  tag: v0.0.4
  imagePullPolicy: Always

imagePullSecrets: []

tolerations: []

resources: {}

loglevel: debug

securityContext: {}

affinity: {}
  # podAntiAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     - topologyKey: "kubernetes.io/hostname"
  #       labelSelector:
  #         matchLabels:
  #           dont-schedule-with: cluster-auditor
  # nodeAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: node-type
  #         operator: In
  #         values:
  #         - "cluster-auditor"

nodeSelector: {}
  # node-type: cluster-auditor

servicemonitor:
  enabled: true
  encryptedMetrics: false

livenessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 3
