apiVersion: v2
name: elasticsearch-kibana
description: A Helm chart for elasticsearch-kibana
version: 0.12.1

maintainers:
- email: tritruong.tr@gmail.com
  name: tritruong

dependencies:
- condition: eck-elasticsearch.enabled
  name: eck-elasticsearch
  repository: https://helm.elastic.co
  version: 0.12.1

- condition: eck-kibana.enabled
  name: eck-kibana
  repository: https://helm.elastic.co
  version: 0.12.1
