{{- if .Values.violations.allowedProcMount.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: {{ .Values.violations.allowedProcMount.kind }}
metadata:
  name: {{ .Values.violations.allowedProcMount.name }}
  labels:
    {{- include "gatekeeper.labels" . | nindent 4 }}
  annotations:
    constraints.gatekeeper/name: "Proc Mount"
    constraints.gatekeeper/description: "Containers may only use the specified ProcMount types."
    constraints.gatekeeper/source: "https://github.com/open-policy-agent/gatekeeper-library/tree/master/library/pod-security-policy/proc-mount"
    constraints.gatekeeper/docs: "https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context-1"
    helm.sh/hook: post-install,post-upgrade
spec:
  enforcementAction: {{ .Values.violations.allowedProcMount.enforcementAction }}
  match:
    {{- if .Values.violations.allowedProcMount.match  }}
    {{- toYaml .Values.violations.allowedProcMount.match | nindent 4}}
    {{- end }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    {{- toYaml .Values.violations.allowedProcMount.parameters | nindent 4}}
{{- end }}