{{- if .Values.violations.allowedAppArmorProfiles.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: {{ .Values.violations.allowedAppArmorProfiles.kind }}
metadata:
  name: {{ .Values.violations.allowedAppArmorProfiles.name }}
  labels:
    {{- include "gatekeeper.labels" . | nindent 4 }}
  annotations:
    constraints.gatekeeper/name: "AppArmor Profile"
    constraints.gatekeeper/description: "Containers may only use specified AppArmor profiles."
    constraints.gatekeeper/source: "https://github.com/open-policy-agent/gatekeeper-library/tree/master/library/pod-security-policy/apparmor"
    constraints.gatekeeper/docs: "https://kubernetes.io/docs/tutorials/clusters/apparmor/#pod-annotation"
    constraints.gatekeeper/related: "https://gitlab.com/apparmor/apparmor"
    helm.sh/hook: post-install,post-upgrade
spec:
  enforcementAction: {{ .Values.violations.allowedAppArmorProfiles.enforcementAction }}
  match:
    {{- if .Values.violations.allowedAppArmorProfiles.match  }}
    {{- toYaml .Values.violations.allowedAppArmorProfiles.match | nindent 4}}
    {{- end }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    {{- toYaml .Values.violations.allowedAppArmorProfiles.parameters | nindent 4}}
{{- end }}