{{- if .Values.violations.containerRatio.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: {{ .Values.violations.containerRatio.kind  }}
metadata:
  name: {{ .Values.violations.containerRatio.name  }}
  labels:
    {{- include "gatekeeper.labels" . | nindent 4 }}
  annotations:
    constraints.gatekeeper/name: "Resource Ratio"
    constraints.gatekeeper/description: "Container resource limits to requests ratio must not be higher than specified."
    constraints.gatekeeper/source: "https://github.com/open-policy-agent/gatekeeper-library/tree/master/library/general/containerresourceratios"
    constraints.gatekeeper/docs: "https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/"
    helm.sh/hook: post-install,post-upgrade
spec:
  enforcementAction: {{ .Values.violations.containerRatio.enforcementAction  }}
  match:
    {{- if .Values.violations.containerRatio.match  }}
    {{- toYaml .Values.violations.containerRatio.match | nindent 4}}
    {{- end }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    {{- toYaml .Values.violations.containerRatio.parameters | nindent 4}}
{{- end }}