{{- if .Values.violations.noDefaultServiceAccount.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: {{ .Values.violations.noDefaultServiceAccount.kind  }}
metadata:
  name: {{ .Values.violations.noDefaultServiceAccount.name  }}
  labels:
    {{- include "gatekeeper.labels" . | nindent 4 }}
  annotations:
    constraints.gatekeeper/name: "Deny Service Account Default"
    constraints.gatekeeper/description: "Pods are not allowed to use default SA."
    constraints.gatekeeper/scope: "Pod"
    constraints.gatekeeper/source: "Unspecified"
    constraints.gatekeeper/docs: "https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server"
    constraints.gatekeeper/related: "https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#serviceaccount-admission-controller"
    helm.sh/hook: post-install,post-upgrade
spec:
  enforcementAction: {{ .Values.violations.noDefaultServiceAccount.enforcementAction  }}
  match:
    {{- if .Values.violations.noDefaultServiceAccount.match  }}
    {{- toYaml .Values.violations.noDefaultServiceAccount.match | nindent 4}}
    {{- end }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    {{- toYaml .Values.violations.noDefaultServiceAccount.parameters | nindent 4}}
{{- end }}