{{- if .Values.violations.restrictedTaint.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: {{ .Values.violations.restrictedTaint.kind }}
metadata:
  name: {{ .Values.violations.restrictedTaint.name }}
  labels:
    {{- include "gatekeeper.labels" . | nindent 4 }}
  annotations:
    constraints.gatekeeper/name: "Taints and Tolerations"
    constraints.gatekeeper/description: "Container must be configured according to specified taint and toleration rules."
    constraints.gatekeeper/source: "https://github.com/stackrox/blog-examples/tree/master/code/opa-gatekeeper-taint-tolerations"
    constraints.gatekeeper/docs: "https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/"
    constraints.gatekeeper/related: "https://www.openshift.com/blog/better-kubernetes-security-with-open-policy-agent-opa-part-2"
    helm.sh/hook: post-install,post-upgrade
spec:
  enforcementAction: {{ .Values.violations.restrictedTaint.enforcementAction }}
  match:
    {{- if .Values.violations.restrictedTaint.match  }}
    {{- toYaml .Values.violations.restrictedTaint.match | nindent 4}}
    {{- end }}
    kinds:
    - apiGroups: [""]
      kinds: ["Pod"]
  parameters:
    {{- toYaml .Values.violations.restrictedTaint.parameters | nindent 4}}
{{- end }}