{{- if and .Values.bigbang.istio.enabled (hasKey .Values.package "istio") (hasKey .Values.package.istio "hardened") (eq (dig "injection" "enabled" .Values.package.istio) "enabled") (dig  "enabled" false .Values.package.istio.hardened) (hasKey .Values.package.istio.hardened "matchLabels") -}}

apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
 name: allow-all-in-namespace
 namespace: {{ .Release.Namespace }}
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: [{{ .Release.Namespace | quote }}]
{{- end }}
