apiVersion: v2
name: fluentd
description: A Helm chart for fluentd
version: 0.5.3

maintainers:
- email: tritruong.tr@gmail.com
  name: tritruong

dependencies:
- name: fluentd
  version: 0.5.2
  repository: https://fluent.github.io/helm-charts
